CREATE TABLE [ELT].[L1TransformInstance] (

	[L1TransformInstanceID] int NOT NULL, 
	[L1TransformID] int NOT NULL, 
	[IngestInstanceID] int NULL, 
	[IngestID] int NOT NULL, 
	[ComputeName] varchar(100) NULL, 
	[ComputePath] varchar(200) NULL, 
	[CustomParameters] varchar(max) NULL, 
	[InputRawFileSystem] varchar(50) NOT NULL, 
	[InputRawFileFolder] varchar(200) NOT NULL, 
	[InputRawFile] varchar(200) NOT NULL, 
	[InputRawFileDelimiter] char(1) NULL, 
	[InputFileHeaderFlag] bit NULL, 
	[OutputL1CurateFileSystem] varchar(50) NOT NULL, 
	[OutputL1CuratedFolder] varchar(200) NOT NULL, 
	[OutputL1CuratedFile] varchar(200) NOT NULL, 
	[OutputL1CuratedFileDelimiter] char(1) NULL, 
	[OutputL1CuratedFileFormat] varchar(10) NULL, 
	[OutputL1CuratedFileWriteMode] varchar(20) NULL, 
	[OutputDWStagingTable] varchar(200) NULL, 
	[LookupColumns] varchar(4000) NULL, 
	[OutputDWTable] varchar(200) NULL, 
	[OutputDWTableWriteMode] varchar(20) NULL, 
	[IngestCount] int NULL, 
	[L1TransformInsertCount] int NULL, 
	[L1TransformUpdateCount] int NULL, 
	[L1TransformDeleteCount] int NULL, 
	[L1TransformStartTimestamp] datetime2(6) NULL, 
	[L1TransformEndTimestamp] datetime2(6) NULL, 
	[L1TransformStatus] varchar(20) NULL, 
	[RetryCount] int NULL, 
	[ActiveFlag] bit NOT NULL, 
	[ReRunL1TransformFlag] bit NULL, 
	[IngestADFPipelineRunID] uniqueidentifier NULL, 
	[L1TransformADFPipelineRunID] uniqueidentifier NULL, 
	[CreatedBy] varchar(128) NOT NULL, 
	[CreatedTimestamp] datetime2(6) NOT NULL, 
	[ModifiedBy] varchar(128) NULL, 
	[ModifiedTimestamp] datetime2(6) NULL
);

